export class Issue {}

export enum IssueType {
    TASK = 'TASK',
    BUG = 'BUG',
    STORY = 'STORY',
}

export enum UpdateIssueEvent {
    SUMMARY_CHANGE = 'SUMMARY_CHANGE',
    DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE',
    TYPE_CHANGE = 'TYPE_CHANGE',
    CATEGORY_CHANGE = 'CATEGORY_CHANGE',
    ASSIGNEE_CHANGE = 'ASSIGNEE_CHANGE',
    SPRINT_CHANGE = 'SPRINT_CHANGE',
}
